# ============================================================================
# Cloud Build Configuration - thiss.link (URL Shortener)
# ============================================================================

steps:
  # --------------------------------------------------------------------------
  # Paso 0: Recuperar .env.local desde Secret Manager (build-time)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'restore-env'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Restoring .env.local from Secret Manager"
        gcloud secrets versions access latest \
          --secret="${_ENV_SECRET_NAME}" > .env.local

  # --------------------------------------------------------------------------
  # Paso 1: Construir imagen Docker (con .env.local disponible)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    waitFor: ['restore-env']
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:latest
      - .

  # --------------------------------------------------------------------------
  # Paso 2: Push imagen (tag build)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    waitFor: ['build-image']
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID

  # --------------------------------------------------------------------------
  # Paso 3: Push imagen (tag latest)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    waitFor: ['build-image']
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:latest

  # --------------------------------------------------------------------------
  # Paso 4: Deploy Cloud Run (Frontend) con variables de entorno desde Secret Manager
  # --------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy-cloud-run'
    waitFor: ['push-image', 'restore-env']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Deploying to Cloud Run with environment variables from Secret Manager"
        
        # Leer el secreto y parsear las variables de entorno de forma segura
        gcloud secrets versions access latest \
          --secret="${_ENV_SECRET_NAME}" > /tmp/env.local
        
        # Construir array de variables de entorno para gcloud
        # Maneja correctamente valores con espacios, comillas, etc.
        declare -a ENV_ARGS=("NODE_ENV=production")
        
        while IFS='=' read -r key value || [ -n "$$key" ]; do
          # Saltar comentarios y líneas vacías
          [[ "$$key" =~ ^[[:space:]]*# ]] && continue
          [[ -z "$$key" ]] && continue
          
          # Remover espacios en blanco del inicio y fin
          key=$$(echo "$$key" | xargs)
          value=$$(echo "$$value" | xargs)
          
          # Remover comillas si existen
          value=$$(echo "$$value" | sed -e 's/^"//' -e 's/"$$//' -e "s/^'//" -e "s/'$$//")
          
          if [ -n "$$key" ] && [ -n "$$value" ]; then
            ENV_ARGS+=("$${key}=$${value}")
          fi
        done < /tmp/env.local
        
        # Convertir array a string separado por comas (escapando $ para bash)
        ENV_VARS_STRING=$$(IFS=','; echo "$${ENV_ARGS[*]}")
        
        # Deploy a Cloud Run con todas las variables de entorno
        # Usar $$ para variables de bash, mantener ${} solo para Cloud Build substitutions
        gcloud run deploy ${_SERVICE_NAME} \
          --image=${_REGION}-docker.pkg.dev/$$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$$BUILD_ID \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --port=3000 \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --concurrency=${_CONCURRENCY} \
          --timeout=${_TIMEOUT} \
          --set-env-vars="$$ENV_VARS_STRING"

# ============================================================================
# Variables de sustitución
# ============================================================================
substitutions:
  _SERVICE_NAME: 'thisslink'
  _REGION: 'us-central1'

  # Artifact Registry
  _AR_REPO: 'thisslink'

  # Firebase
  _FIREBASE_PROJECT_ID: 'innovadev-core-prod'

  # Cloud Run sizing
  _MEMORY: '512Mi'
  _CPU: '1'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '100'
  _TIMEOUT: '300'

  # Secret Manager
  _ENV_SECRET_NAME: 'thisslink-env-local'

# ============================================================================
# Build options
# ============================================================================
options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:latest
