# ============================================================================
# Cloud Build Configuration - thiss.link (URL Shortener)
# ============================================================================

steps:
  # --------------------------------------------------------------------------
  # Paso 0: Recuperar .env.local desde Secret Manager (build-time)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'restore-env'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Restoring .env.local from Secret Manager"
        gcloud secrets versions access latest \
          --secret="${_ENV_SECRET_NAME}" > .env.local

  # --------------------------------------------------------------------------
  # Paso 1: Construir imagen Docker (con .env.local disponible)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    waitFor: ['restore-env']
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:latest
      - .

  # --------------------------------------------------------------------------
  # Paso 2: Push imagen (tag build)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    waitFor: ['build-image']
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID

  # --------------------------------------------------------------------------
  # Paso 3: Push imagen (tag latest)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    waitFor: ['build-image']
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:latest

  # --------------------------------------------------------------------------
  # Paso 4: Instalar dependencias, compilar y desplegar Firebase Functions
  # El predeploy hook de firebase.json ejecutará lint y build automáticamente,
  # pero primero necesitamos instalar las dependencias.
  # --------------------------------------------------------------------------
  - name: 'node:22'
    id: 'deploy-functions'
    waitFor: ['build-image', 'restore-env']
    entrypoint: 'bash'
    args:
      - -c
      - |
        cd functions
        npm ci
        # Instalar Firebase CLI globalmente
        npm install -g firebase-tools
        # El deploy ejecutará automáticamente el predeploy hook (lint + build)
        # --force configura automáticamente la cleanup policy para evitar costos por imágenes acumuladas
        # Nota: NEXT_PUBLIC_BASE_URL debe configurarse manualmente en Firebase Console
        # o usando: firebase functions:config:set app.base_url="https://go.innovadev.com.co/" --project=${_FIREBASE_PROJECT_ID}
        firebase deploy --only=functions --project=${_FIREBASE_PROJECT_ID} --non-interactive --force

  # --------------------------------------------------------------------------
  # Paso 5: Deploy Cloud Run (Frontend)
  # --------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=3000
      - --memory=${_MEMORY}
      - --cpu=${_CPU}
      - --min-instances=${_MIN_INSTANCES}
      - --max-instances=${_MAX_INSTANCES}
      - --concurrency=${_CONCURRENCY}
      - --timeout=${_TIMEOUT}
      - --set-env-vars=NODE_ENV=production

# ============================================================================
# Variables de sustitución
# ============================================================================
substitutions:
  _SERVICE_NAME: 'thisslink'
  _REGION: 'us-central1'

  # Artifact Registry
  _AR_REPO: 'thisslink'

  # Firebase
  _FIREBASE_PROJECT_ID: 'innovadev-core-prod'

  # Cloud Run sizing
  _MEMORY: '512Mi'
  _CPU: '1'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '100'
  _TIMEOUT: '300'

  # Secret Manager
  _ENV_SECRET_NAME: 'thisslink-env-local'

# ============================================================================
# Build options
# ============================================================================
options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:latest
